Assignment-war/src/fit5042/assign/mbeans/ContactManagedBean.java
package fit5042.assign.mbeans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.validation.spi.ValidationProvider;

import fit5042.assign.controller.ContactBean;
import fit5042.assign.repository.ContactRepository;
import fit5042.assign.repository.entities.Address;
import fit5042.assign.repository.entities.ConDomestic;
import fit5042.assign.repository.entities.ConInternational;
import fit5042.assign.repository.entities.Contact;
import fit5042.assign.repository.entities.Customer;

@ManagedBean(name="contactManagedBean")
@SessionScoped
public class ContactManagedBean implements Serializable {

	@EJB
	ContactRepository contactRepository;

	private UIComponent component;

    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }
	
	public ContactManagedBean() {
	}
	
	public void addContact(Contact contact) {
		try {
			contactRepository.addContact(contact);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void addContactFirst() {
		Contact contact = getAllContacts().get(0);
		addContact(contact);		
	}
	
	public Contact searchContactById(int contactId) {
		try {
			return contactRepository.searchContactById(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public Set<Contact> searchContactByCustomerId(int customerId) {
		// TODO Auto-generated method stub
		try {
			for (Customer customer : contactRepository.getAllCustomers()) {
                if (customer.getCustomerId() == customerId) {
                    return contactRepository.searchContactByCustomer(customer);
                }
			}
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}	
	
	public List<Contact> getAllContacts(){
		try {
			return contactRepository.getAllContacts();
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public void removeContact(int contactId) {
		try {
			contactRepository.removeContact(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void editContact(Contact contact) {
		try {
			contactRepository.editContact(contact);
			FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Contact Updated !!"));
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}

	
//	-----------------------------------------------
	
	private Contact convertContactBeanToEntity(ContactBean localContact) {
		Contact contact = new Contact();
		String firstName = localContact.getFirstName();
		String lastName = localContact.getLastName();
		String position = localContact.getPosition();
		String email = localContact.getEmail();
		String phoneNo = localContact.getPhoneNo();
		String preference = localContact.getPreference();
		
		contact.setFirstName(firstName);
		contact.setLastName(lastName);
		contact.setPosition(position);
		contact.setEmail(email);
		contact.setPhoneNo(phoneNo);
		contact.setPreference(preference);
		
		int customerId = localContact.getCustomerId();
		Customer customer = new Customer();
		try {
			for (Customer customerElement : contactRepository.getAllCustomers()) {
			    if (customerElement.getCustomerId() == customerId) {
			        customer = customerElement;
			    }
			}
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
		
		contact.setCustomer(customer);

		
		return contact;
	}
	
	public void addContact(ContactBean localContact) {
		Contact contact = convertContactBeanToEntity(localContact);
		addContact(contact);	
	}

//	----------------------------------------------------------------
	
	public List<Contact> searchContactsByPositionAndPreference(String position, String preference) {
		List<Contact> output = new ArrayList<>();
		try {
            boolean contentCheck = false;
            for (Contact contact : contactRepository.getAllContacts()) {
                String position1 = contact.getPosition();
                String preference1 = contact.getPreference();
                if(!position.equals("") && !preference.equals("")) {
                	contentCheck = true;
                	if(position.equals(position1) && preference.equals(preference1))
                    	output.add(contact); 
                }else if(position.equals("") && !preference.equals("")) {
                	contentCheck = true;
                	if(preference.equals(preference1))
                		output.add(contact); 
                }else if(!position.equals("") && preference.equals("")) {
                	contentCheck = true;
                	if(position.equals(position1))
                		output.add(contact); 
                }                               	
            }            
//            if(!contentCheck) {
//            	FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("NO INPUT, please select a industry and/or enter a year!!"));
//            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }		
		return output;
	}
	
	public Set<String> getAllPosition(){
		Set<String> outputs = new HashSet<String>();
		try {
			List<Contact> contacts = contactRepository.getAllContacts();
			for (Contact contact : contacts) {
				String position = contact.getPosition();
				outputs.add(position);					
			}			
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return outputs;
	}
	

	
	
	
//	================================================================
	// FOR CON-DOMESTIC
	
	public List<ConDomestic> getAllConDomestics(){
		try {
			return contactRepository.getAllConDomestics();
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	
	public void removeConDomestic(int contactId) {
		try {
			contactRepository.removeConDomestic(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void editConDomestic(ConDomestic contact) {
		try {
			contactRepository.editConDomestic(contact);
			FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Domestic Contact Updated !!"));
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	private ConDomestic convertBeanToDomesticEntity(ContactBean localContact) {
//		Contact contact = new Contact();
		ConDomestic contact = new ConDomestic();
		
		String firstName = localContact.getFirstName();
		String lastName = localContact.getLastName();
		String position = localContact.getPosition();
		String email = localContact.getEmail();
		String phoneNo = localContact.getPhoneNo();
		String preference = localContact.getPreference();
		
		contact.setFirstName(firstName);
		contact.setLastName(lastName);
		contact.setPosition(position);
		contact.setEmail(email);
		contact.setPhoneNo(phoneNo);
		contact.setPreference(preference);
		
		contact.setState(localContact.getState());
		
		int customerId = localContact.getCustomerId();
		Customer customer = new Customer();
		try {
			for (Customer customerElement : contactRepository.getAllCustomers()) {
			    if (customerElement.getCustomerId() == customerId) {
			        customer = customerElement;
			    }
			}
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
		contact.setCustomer(customer);

		return contact;
	}
	
	public void addConDomestic(ContactBean localContact) {
		ConDomestic conDomestic = convertBeanToDomesticEntity(localContact);
		try {
			contactRepository.addConDomestic(conDomestic);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}		
	}

	
//	==============================================================
	// FOR CON-INTERNATIONAL
	
	public List<ConInternational> getAllConInternationals(){
		try {
			return contactRepository.getAllConInternationals();
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public void removeConInternational(int contactId) {
		try {
			contactRepository.removeConInternational(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void editConInternational(ConInternational contact) {
		try {
			contactRepository.editConInternational(contact);
			FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("International Contact Updated !!"));
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	private ConInternational convertBeanToInternationalEntity(ContactBean localContact) {
//		Contact contact = new Contact();
		ConInternational contact = new ConInternational();
		
		String firstName = localContact.getFirstName();
		String lastName = localContact.getLastName();
		String position = localContact.getPosition();
		String email = localContact.getEmail();

Assignment-war/src/fit5042/assign/mbeans/IndustryManagedBean.java
package fit5042.assign.mbeans;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

import fit5042.assign.controller.IndustryBean;
import fit5042.assign.repository.IndustryRepository;
import fit5042.assign.repository.entities.Industry;

@ManagedBean(name="industryManagedBean")
@SessionScoped
public class IndustryManagedBean implements Serializable{

	@EJB
	IndustryRepository industryRepository;
	
	private UIComponent component;
	
	public UIComponent getComponent() {
		return component;
	}

	public void setComponent(UIComponent component) {
		this.component = component;
	}

	public IndustryManagedBean() {
		super();
	}
	
	public void addIndustry(Industry industry) {
		try {
			industryRepository.addIndustry(industry);
		} catch (Exception e) {
			Logger.getLogger(IndustryManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void addIndustryFirst() {
		Industry industry = getAllIndustries().get(0);
		addIndustry(industry);
	}
	
	public Industry searchIndustryById(int industryId) {
		try {
			industryRepository.searchIndustryById(industryId);
		} catch (Exception e) {
			Logger.getLogger(IndustryManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public List<Industry> getAllIndustries(){
		try {
			List<Industry> industries = industryRepository.getAllIndustries();
			return industries;
		} catch (Exception e) {
			Logger.getLogger(IndustryManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public void removeIndustry(int industryId) {
		try {
			industryRepository.removeIndustry(industryId);
		} catch (Exception e) {
			Logger.getLogger(IndustryManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
	}
	
	public void editIndustry(Industry industry) {
		try {
			industryRepository.editIndustry(industry);
			FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Industry Updated !!"));
		} catch (Exception e) {
			Logger.getLogger(IndustryManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
	}
	
//	------------------------------------------------------
	private Industry convertIndustryBeanToEntity(IndustryBean localIndustry) {
		Industry industry = new Industry();
		String industryType = localIndustry.getIndustryType();
		industry.setIndustryType(industryType);
		
		industry.setCustomers(null);
		
		return industry;		
	}
	
	public void addIndustry(IndustryBean localIndustry) {
		Industry industry = convertIndustryBeanToEntity(localIndustry);
		addIndustry(industry);
	}
	
}

Assignment-war/WebContent/normal/contactlist.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
    <title>#{titleController.pageTitle}</title>
    <script src="js/script.js"></script>
    <script src="https://cdn.staticfile.org/angular.js/1.4.6/angular.min.js"></script>
</h:head> 
<body> 
	<div class="container">
		<!-- https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
		<div class="navbar navbar-dark bg-info flex-column flex-md-row bd-navbar">
		    <a class="navbar-brand" href="#">
		    	<img src="../resources/image/icons8-member-50.png" width="25" height="25" alt=""></img>
		      	#{customerApplication.username} - Contact  List</a>
		    <div class="navbar-nav-scroll">
			   <ul class="navbar-nav bd-navbar-nav flex-row">
			      <li class="nav-item"><a class="nav-link" href="customerlist.xhtml">Customer  &nbsp; &nbsp;</a></li>
			      <li class="nav-item active"><a class="nav-link" href="#">Contact  &nbsp; &nbsp;</a></li>
			      <li class="nav-item"><a class="nav-link" href="stafflist.xhtml">User  </a></li>
			    </ul>
			</div>
			<a href="${pageContext.request.contextPath}/Assignment-war/logout" 
			class="btn btn-outline-light btn-sm my-2 my-sm-0"
			onclick="if (!confirm('Are you sure to log out?')) return false;">
			Logout</a>  
		</div>
		
		<br/>
        
        <h:form id="MyForm1">
        
        	<!-- FOR CON-DOMESTIC -->
        	<p>Domestic Contacts: </p>
        	
        	<table class="table table-sm table-bordered table-striped">
        		<!-- For each contact in ArrayList... -->
        		<!-- column name -->
        		<tr>
        			<td>
                        <h:outputLabel id="Id" value="Id"  />
                    </td>
                    <td>
                        <h:outputLabel id="FirstName" value="First Name"  />
                    </td>
                    <td>
                        <h:outputLabel id="LastName" value="Last Name"  />
                    </td>
                    <td>
                        <h:outputLabel id="Email" value="Email"/>
                    </td>
                    <td>
                        <h:outputLabel id="PhoneNo" value="PhoneNo"/>
                    </td>
                    <td>
                        <h:outputLabel id="State" value="State"/>
                    </td>
                    <td>
                        <h:outputLabel id="Option" value="Option"/>
                    </td>

        		</tr>
        	
				<!-- table content -->
        		<ui:repeat id="Myrepeat" value="#{contactApplication.conDomestics}"  var="contact" varStatus="status">

	                <tr onclick="document.getElementById('MyForm:principle').value = document.getElementById('MyForm:Myrepeat:#{status.index}:outPrice').textContent">
	                    <td>
	                        <h:outputText id="contactID" value="#{contactApplication.conDomestics.get(status.index).contactId}"/>
	                    </td>
	                    <td>
	                        <h:outputText id="outFirstName" value="#{contactApplication.conDomestics.get(status.index).firstName}"  />
	                    </td>
	                    <td>
	                        <h:outputText id="outLastName" value="#{contactApplication.conDomestics.get(status.index).lastName}"  />
	                    </td>
	                    <td>
	                        <h:outputText id="outEmail" value="#{contactApplication.conDomestics.get(status.index).email}"/>
	                    </td>	                    
	                    <td>
	                        <h:outputText id="outPhoneNo" value="#{contactApplication.conDomestics.get(status.index).phoneNo}"/>
	                    </td>
	                    <td>
	                        <h:outputText id="outState" value="#{contactApplication.conDomestics.get(status.index).state}"/>
	                    </td>

						<!-- FUNCTION FOR EACH CONTACT -->
	                    <td>
	                        <h:link value="View" class="btn btn-outline-info btn-sm" outcome="condomesticdetail.xhtml">
	                        <!-- pass the parameter to next page, the param name is contactID, and the value is index + 1.
	                        You can get the value from next page using the indexController -->
	                        <f:param name="contactID" value="#{status.index + 1}"/>
	                        </h:link>
							&nbsp;
	                        <h:link value="Edit" class="btn btn-outline-info btn-sm" outcome="condomesticedit.xhtml">
	                        <!-- pass the parameter to next page, the param name is contactID, and the value is index + 1.
	                        You can get the value from next page using the indexController -->
	                        <f:param name="contactID" value="#{status.index + 1}"/>
	                        </h:link>
	                        &nbsp;
	                        <h:commandLink value="Delete" class="btn btn-outline-danger btn-sm"
	                        action="#{contactRemove.conDomesticRemove(contactApplication.conDomestics.get(status.index).contactId)}" 
	                        onclick="if (!confirm('Are you sure to delete it?')) return false;"
	                        >
                            </h:commandLink>
	                        
	                        <h:outputText value=" "/>
	                    </td>
	
	                </tr>

                </ui:repeat>
        	
        	</table>
        	
        </h:form>
        	
       	<h:form id="MyForm2">
       	
        	<!-- FOR CON-INTERNATIONAL -->
        	
        	<p>International Contacts: </p>
        	
        	<table class="table table-sm table-bordered table-striped">
        		<!-- For each contact in ArrayList... -->
        		<!-- column name -->
        		<tr>
        			<td>
                        <h:outputLabel id="Id2" value="Id"  />
                    </td>
                    <td>
                        <h:outputLabel id="FirstName2" value="First Name"  />
                    </td>
                    <td>
                        <h:outputLabel id="LastName2" value="Last Name"  />
                    </td>
                    <td>
                        <h:outputLabel id="Email2" value="Email"/>
                    </td>
                    <td>
                        <h:outputLabel id="PhoneNo2" value="PhoneNo"/>
                    </td>
                    <td>
                        <h:outputLabel id="Country" value="Country"/>
                    </td>
                    <td>
                        <h:outputLabel id="Option2" value="Option"/>
                    </td>

        		</tr>
        	
				<!-- table content -->
        		<ui:repeat id="Myrepeat" value="#{contactApplication.conInternationals}"  var="contact" varStatus="status">

	                <tr onclick="document.getElementById('MyForm:principle').value = document.getElementById('MyForm:Myrepeat:#{status.index}:outPrice').textContent">
	                    <td>
	                        <h:outputText id="contactID2" value="#{contactApplication.conInternationals.get(status.index).contactId}"/>
	                    </td>
	                    <td>
	                        <h:outputText id="outFirstName2" value="#{contactApplication.conInternationals.get(status.index).firstName}"  />
	                    </td>
	                    <td>
	                        <h:outputText id="outLastName2" value="#{contactApplication.conInternationals.get(status.index).lastName}"  />
	                    </td>
	                    <td>
	                        <h:outputText id="outEmail2" value="#{contactApplication.conInternationals.get(status.index).email}"/>
	                    </td>	                    
	                    <td>
	                        <h:outputText id="outPhoneNo2" value="#{contactApplication.conInternationals.get(status.index).phoneNo}"/>
	                    </td>
	                    <td>
	                        <h:outputText id="outCountry" value="#{contactApplication.conInternationals.get(status.index).country}"/>
	                    </td>

						<!-- FUNCTION FOR EACH CONTACT -->
	                    <td>
	                        <h:link value="View" outcome="coninternationaldetail.xhtml" class="btn btn-outline-info btn-sm">
	                        <!-- pass the parameter to next page, the param name is contactID, and the value is index + 1.
	                        You can get the value from next page using the indexController -->
	                        <f:param name="contactID" value="#{status.index + 1}"/>
	                        </h:link>
							&nbsp;
	                        <h:link value="Edit" outcome="coninternationaledit.xhtml" class="btn btn-outline-info btn-sm">
	                        <!-- pass the parameter to next page, the param name is contactID, and the value is index + 1.
	                        You can get the value from next page using the indexController -->
	                        <f:param name="contactID" value="#{status.index + 1}"/>
	                        </h:link>
	                        &nbsp;
	                        <h:commandLink value="Delete" class="btn btn-outline-danger btn-sm"
	                        action="#{contactRemove.conInternationalRemove(contactApplication.conInternationals.get(status.index).contactId)}" 
	                        disabled="#{contactApplication.conInternationals.get(status.index).contactId == null}"
	                        onclick="if (!confirm('Are you sure to delete it?')) return false;">
                            </h:commandLink>
	                        
	                        <h:outputText value=" "/>
	                    </td>
	
	                </tr>

                </ui:repeat>
        	
        	</table>
        	
        	

        	<!-- GENERAL FUNCTION : add / search /...... -->
        	<div>

				<h:commandButton id="addDomestic" value="Add Domestic Contact" action="condomesticadd.xhtml" class="btn btn-info" />
				&nbsp; &nbsp;
				<h:commandButton id="addInternational" value="Add Intl. Contact" action="coninternationaladd.xhtml" class="btn btn-info" />
				&nbsp; &nbsp;
	        	<h:commandButton id="viewAll" value="View All" action="#{contactSearch.searchAll()}" class="btn btn-info" >
	                <f:param name="contactID" value="#{status.index + 1}"/>
	            </h:commandButton>
	            &nbsp; &nbsp;
	            <h:commandButton id="viewCoutnry" value="Modify Country List" action="countrydetail.xhtml" class="btn btn-secondary" />
	            
        	</div>
        	
        	<div>
        		<h:outputText id="test" binding="#{contactRemove.component}"/>
				<h:message for="test" infoClass="info" globalOnly ="true" style="color:blue"/>
        	</div>        	
        	
        	<br/>
       	</h:form>
        	
       	<h:form id="MyForm3">
        	<div>
        		
        		<h:inputText value="#{contactSearch.contactId}" 
        		id="searchById" required="true"
        		onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "  />
        		&nbsp;
        		<h:commandButton id="searchId" value="Search by Id" 
        		action="#{contactSearch.searchContactById(contactSearch.contactId)}" 
        		class="btn btn-info" >
                    <f:param name="contactID" value="#{status.index + 1}"/>
                </h:commandButton>
                &nbsp; &nbsp;
            </div>
        	<br/>
       	</h:form>
        	
        <h:form id="MyForm4">
        	<div>
                <h:selectOneMenu id="customer" value="#{customerSearch.searchByInt}" >
	                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
	                <f:selectItems value="#{customerApplication.getCustomers()}" var="c"
	                                itemLabel="#{c.customerName}" itemValue="#{c.customerId}" />
	            </h:selectOneMenu>
	            &nbsp;
	            <h:commandButton id="searchByCustomer" value="Search by Customer" 
	            action="#{contactSearch.searchContactByCustomerId(customerSearch.searchByInt)}" 
	            class="btn btn-info" >
	                <f:param name="contactID" value="#{status.index + 1}"/>
	            </h:commandButton>
                
        	</div>
        	<br/>
       	
       	</h:form>
        	
        <h:form id="MyForm5">

        	<div>
        		<h:selectOneMenu id="position" value="#{contactSearch.position}" >
	                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
	                <f:selectItems value="#{contactManagedBean.allPosition}" var="c"
	                                itemLabel="#{c}" itemValue="#{c}" />
	            </h:selectOneMenu>
        		&nbsp;
        		<h:selectOneMenu id="preference" value="#{contactSearch.preference}">
                        <f:selectItem itemValue="#{null}" itemLabel="--select--" /> <!-- noSelectionOption="true" -->
                        <f:selectItem itemValue="ContactByEmail" itemLabel="ContactByEmail" />
                        <f:selectItem itemValue="ContactByPhone" itemLabel="ContactByPhone" />
                </h:selectOneMenu> 
	            &nbsp;	            
        		<h:commandButton id="searchByPreAndPos" value="Search by Position / Preference" 
	            action="#{contactSearch.searchContactsByPositionAndPreference(contactSearch.position, contactSearch.preference)}" 
	            class="btn btn-info" >
	                <f:param name="contactID" value="#{status.index + 1}"/>
	            </h:commandButton>   	
        	
        	</div>
        	
        </h:form>        
	
	</div>

</body> 
</html>

Assignment-war/WebContent/normal/industryadd.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"> 

<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
    <title>#{titleController.pageTitle}</title>
</h:head> 
<body> 
	<div class="container">
		<div class="navbar navbar-inverse">
	        <div class="navbar-brand">
	        	<img src="../resources/image/icons8-member-50.png" width="25" height="25" alt=""></img>
				#{customerApplication.username} - Add Industry
	        </div>
        </div>
		
		<h:form id="MyForm1">
			<table class="table table-bordered ">
				
				<tr>
					<td width ="100" valign="top">Industry Type:</td>
                    <td valign="bottom">
                        <h:inputText id = "industryType" 
                        value="#{industryBean.industryType}" 
                        title="industryType"
                        required="true"
                        validatorMessage="Please enter a valid Industry Type."
                        requiredMessage="Please enter an Industry Type. "
                        pt:placeholder="Construction">
                        </h:inputText>
                        <br/>
                        <h:message for="industryType" 
                        class="#{!industryType.valid ? 'label label-warning' : 'none'}" />
                        
                    </td>			
				</tr>
				
			</table>
			
			<p>If all inputs are valid, it will redirect to "Industry List" page once clicking "Submit" button.</p>
			
			<h:commandButton id="submit" value="Submit and Close"
			actionListener="#{industryAdd.industryAdd(industryBean)}"
			action="industrylist?faces-redirect=true"
			class="btn btn-primary" />

			<h:link id="close" value="Close" 
			outcome="industrylist.xhtml" class="btn btn-primary" style="float:right"/>
			
			<br/>
			<br/>
        	<h:outputText id="test" binding="#{industryAdd.component}"/>
			<h:message for="test" infoClass="info" globalOnly ="true" style="color:blue"/>

		</h:form>
	</div>
</body> 
</html>