Assignment-war/src/fit5042/assign/mbeans/ContactManagedBean.java
package fit5042.assign.mbeans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.validation.spi.ValidationProvider;

import fit5042.assign.controller.ContactBean;
import fit5042.assign.repository.ContactRepository;
import fit5042.assign.repository.entities.Address;
import fit5042.assign.repository.entities.ConDomestic;
import fit5042.assign.repository.entities.ConInternational;
import fit5042.assign.repository.entities.Contact;
import fit5042.assign.repository.entities.Customer;

@ManagedBean(name="contactManagedBean")
@SessionScoped
public class ContactManagedBean implements Serializable {

	@EJB
	ContactRepository contactRepository;

	private UIComponent component;

    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }
	
	public ContactManagedBean() {
	}
	
	public void addContact(Contact contact) {
		try {
			contactRepository.addContact(contact);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void addContactFirst() {
		Contact contact = getAllContacts().get(0);
		addContact(contact);		
	}
	
	public Contact searchContactById(int contactId) {
		try {
			return contactRepository.searchContactById(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public Set<Contact> searchContactByCustomerId(int customerId) {
		// TODO Auto-generated method stub
		try {
			for (Customer customer : contactRepository.getAllCustomers()) {
                if (customer.getCustomerId() == customerId) {
                    return contactRepository.searchContactByCustomer(customer);
                }
			}
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}	
	
	public List<Contact> getAllContacts(){
		try {
			return contactRepository.getAllContacts();
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public void removeContact(int contactId) {
		try {
			contactRepository.removeContact(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void editContact(Contact contact) {
		try {
			contactRepository.editContact(contact);
			FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Contact Updated !!"));
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}

	
//	-----------------------------------------------
	
	private Contact convertContactBeanToEntity(ContactBean localContact) {
		Contact contact = new Contact();
		String firstName = localContact.getFirstName();
		String lastName = localContact.getLastName();
		String position = localContact.getPosition();
		String email = localContact.getEmail();
		String phoneNo = localContact.getPhoneNo();
		String preference = localContact.getPreference();
		
		contact.setFirstName(firstName);
		contact.setLastName(lastName);
		contact.setPosition(position);
		contact.setEmail(email);
		contact.setPhoneNo(phoneNo);
		contact.setPreference(preference);
		
		int customerId = localContact.getCustomerId();
		Customer customer = new Customer();
		try {
			for (Customer customerElement : contactRepository.getAllCustomers()) {
			    if (customerElement.getCustomerId() == customerId) {
			        customer = customerElement;
			    }
			}
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
		
		contact.setCustomer(customer);

		
		return contact;
	}
	
	public void addContact(ContactBean localContact) {
		Contact contact = convertContactBeanToEntity(localContact);
		addContact(contact);	
	}

//	----------------------------------------------------------------
	
	public List<Contact> searchContactsByPositionAndPreference(String position, String preference) {
		List<Contact> output = new ArrayList<>();
		try {
            boolean contentCheck = false;
            for (Contact contact : contactRepository.getAllContacts()) {
                String position1 = contact.getPosition();
                String preference1 = contact.getPreference();
                if(!position.equals("") && !preference.equals("")) {
                	contentCheck = true;
                	if(position.equals(position1) && preference.equals(preference1))
                    	output.add(contact); 
                }else if(position.equals("") && !preference.equals("")) {
                	contentCheck = true;
                	if(preference.equals(preference1))
                		output.add(contact); 
                }else if(!position.equals("") && preference.equals("")) {
                	contentCheck = true;
                	if(position.equals(position1))
                		output.add(contact); 
                }                               	
            }            
//            if(!contentCheck) {
//            	FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("NO INPUT, please select a industry and/or enter a year!!"));
//            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }		
		return output;
	}
	
	public Set<String> getAllPosition(){
		Set<String> outputs = new HashSet<String>();
		try {
			List<Contact> contacts = contactRepository.getAllContacts();
			for (Contact contact : contacts) {
				String position = contact.getPosition();
				outputs.add(position);					
			}			
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return outputs;
	}
	

	
	
	
//	================================================================
	// FOR CON-DOMESTIC
	
	public List<ConDomestic> getAllConDomestics(){
		try {
			return contactRepository.getAllConDomestics();
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	
	public void removeConDomestic(int contactId) {
		try {
			contactRepository.removeConDomestic(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void editConDomestic(ConDomestic contact) {
		try {
			contactRepository.editConDomestic(contact);
			FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Domestic Contact Updated !!"));
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	private ConDomestic convertBeanToDomesticEntity(ContactBean localContact) {
//		Contact contact = new Contact();
		ConDomestic contact = new ConDomestic();
		
		String firstName = localContact.getFirstName();
		String lastName = localContact.getLastName();
		String position = localContact.getPosition();
		String email = localContact.getEmail();
		String phoneNo = localContact.getPhoneNo();
		String preference = localContact.getPreference();
		
		contact.setFirstName(firstName);
		contact.setLastName(lastName);
		contact.setPosition(position);
		contact.setEmail(email);
		contact.setPhoneNo(phoneNo);
		contact.setPreference(preference);
		
		contact.setState(localContact.getState());
		
		int customerId = localContact.getCustomerId();
		Customer customer = new Customer();
		try {
			for (Customer customerElement : contactRepository.getAllCustomers()) {
			    if (customerElement.getCustomerId() == customerId) {
			        customer = customerElement;
			    }
			}
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
		contact.setCustomer(customer);

		return contact;
	}
	
	public void addConDomestic(ContactBean localContact) {
		ConDomestic conDomestic = convertBeanToDomesticEntity(localContact);
		try {
			contactRepository.addConDomestic(conDomestic);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}		
	}

	
//	==============================================================
	// FOR CON-INTERNATIONAL
	
	public List<ConInternational> getAllConInternationals(){
		try {
			return contactRepository.getAllConInternationals();
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public void removeConInternational(int contactId) {
		try {
			contactRepository.removeConInternational(contactId);
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void editConInternational(ConInternational contact) {
		try {
			contactRepository.editConInternational(contact);
			FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("International Contact Updated !!"));
		} catch (Exception e) {
			Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	private ConInternational convertBeanToInternationalEntity(ContactBean localContact) {
//		Contact contact = new Contact();
		ConInternational contact = new ConInternational();
		
		String firstName = localContact.getFirstName();
		String lastName = localContact.getLastName();
		String position = localContact.getPosition();
		String email = localContact.getEmail();

Assignment-war/src/fit5042/assign/mbeans/StaffManagedBean.java
package fit5042.assign.mbeans;

import java.io.Serializable;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

import fit5042.assign.controller.StaffBean;
import fit5042.assign.repository.GroupsRepository;
import fit5042.assign.repository.StaffRepository;
import fit5042.assign.repository.entities.Groups;
import fit5042.assign.repository.entities.Staff;

@ManagedBean(name="staffManagedBean")
@SessionScoped
public class StaffManagedBean implements Serializable {
	
	@EJB
	StaffRepository staffRepository;
	
	@EJB
	GroupsRepository groupsRepository;
	
	private UIComponent component;
	
	private boolean showButton = true;
	
    public boolean isShowButton() {
		return showButton;
	}

	public void setShowButton(boolean showButton) {
		this.showButton = showButton;
	}
	
	private boolean disableButton = false;

	public boolean isDisableButton() {
		return disableButton;
	}

	public void setDisableButton() {
		this.disableButton = false;
	}

	public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }

	public StaffManagedBean() {
		super();
		disableButton = false;
	}
    
	public void addStaff(Staff staff) {
		try {
			//HASH the password
			String password = staff.getPassword();
			password = convertToHash(password);
			staff.setPassword(password);
			
			staffRepository.addStaff(staff);
			
			//add the staff to the group;
//			int id = staff.getId();
			String userName = staff.getUsername();
			Groups groups = new Groups();
			groups.setGroupname("normal");
//			groups.setId(id);
			groups.setUsername(userName);
			groupsRepository.addGroups(groups);
			
			showButton = false;
			disableButton = true;
			
		} catch (Exception e) {
			Logger.getLogger(StaffManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	
	public void addStaffFirst() {
		Staff staff = getAllStaffs().get(0);
		addStaff(staff);
	}
	
	public Staff searchStaffById(int id) {
		try {
			return staffRepository.searchStaffById(id);
		} catch (Exception e) {
			Logger.getLogger(StaffManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public int searchIDByUsername(String username) {
		try {
			List<Staff> staffs = staffRepository.getAllStaffs();
			for (Staff staff: staffs) {
				if(username.equals(staff.getUsername())){
					int staffId = staff.getId();
					return staffId;
				}
			}			
		} catch (Exception e) {
			Logger.getLogger(StaffManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return -1;
	}
	
	public List<Staff> getAllStaffs() {
		try {
			List<Staff> staffs = staffRepository.getAllStaffs();
			List<Staff> output = new ArrayList<>();
			//return normal user only.
			for(Staff staffElement : staffs) {
				if (staffElement.getUserType().toUpperCase().equals("NORMAL"))
					output.add(staffElement);
			}
			return output;
		} catch (Exception e) {
			Logger.getLogger(StaffManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		return null;
	}
	
	public void removeStaff(int id) {
		try {
			staffRepository.removeStaff(id);
			//remove  the relevant group record.
			groupsRepository.removeGroups(id);
		} catch (Exception e) {
			Logger.getLogger(StaffManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
	}
	
	public void editStaff(Staff staff) {
		try {
			//check username
			int check = checkUsername(staff.getUsername(), staff.getId());
			if(check!=1 && check!=2) {
				//HASH the password
				String password = staff.getPassword();
				password = convertToHash(password);
				//compare the password
				int id = staff.getId();
				String passwordOrg = searchStaffById(id).getPassword();
				if(passwordOrg.equals(password)) {
					FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("UPDATE FAILED!! NEW password must be differernt from the old one!!"));
				}else {
					//update staff vaule
					staff.setPassword(password);
					staffRepository.editStaff(staff);
					
					//edit the relevant groups (username);
					String userName = staff.getUsername();
//					int id = staff.getId();
					Groups groups = new Groups();
					groups.setId(id);
					groups.setGroupname("normal");
					groups.setUsername(userName);
					groupsRepository.editGroups(groups);

					FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Staff Updated !! Please click CLOSE button!!"));
					
					showButton = false;
					disableButton = true;
				}
			}
			
		} catch (Exception e) {
			Logger.getLogger(StaffManagedBean.class.getName()).log(Level.SEVERE, null, e);
		}
		
	}
	
//	-----------------------------------------------------
	private Staff covertStaffBeanToEntity(StaffBean localStaff) {
		Staff staff = new Staff();
		String username = localStaff.getUsername();
		String password = localStaff.getPassword();
		staff.setUsername(username);
		staff.setPassword(password);
		staff.setUserType("NORMAL");
		
		staff.setCustomers(null);
		
		return staff;		
	}
    
	public void addStaff(StaffBean localStaff) {
		Staff staff = covertStaffBeanToEntity(localStaff);
		addStaff(staff);
	}
	
	
//	-----------------------------------------------------------
	
	public String convertToHash(String passwordStr) throws NoSuchAlgorithmException {
		
//		https://stackoverflow.com/questions/3103652/hash-string-via-sha-256-in-java?rq=1
		MessageDigest md = MessageDigest.getInstance("SHA-256");

	    md.update(passwordStr.getBytes(StandardCharsets.UTF_8));
	    byte[] digest = md.digest();

	    String hex = String.format("%064x", new BigInteger(1, digest));
//	    System.out.println(hex);
		return hex;
	}
	
//	---------------------------------------------------
	
	public int checkUsername(String username, int id) {
		int check = 0;
//		String username = localStaff.getUsername();
		
		if(username.toLowerCase().equals("null")) {
			check = 1;
			if (id!=-1)
				FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Username cannot be null !!"));
			return check;
		}
		
		List<Staff> staffs = getAllStaffs();
		for (Staff staff: staffs) {
			String username1 = staff.getUsername();
			int id2 = staff.getId();
			if(username.equals(username1) && id!=id2) {
				check = 2;
				if(id!=-1)
					FacesContext.getCurrentInstance().addMessage(component.getClientId(), new FacesMessage("Username exist!! please enter another username"));
				return check;
			}
				
		}
		return check;
	}
	
	
	
}

Assignment-war/WebContent/admin/customerlist.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"> 

<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
    <title>#{titleController.pageTitle}</title>
    <script src="../resources/js/script.js"></script>
    <script src="https://cdn.staticfile.org/angular.js/1.4.6/angular.min.js"></script>
</h:head> 
<body> 
	<div class="container">
		<!-- https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
      	<div class="navbar navbar-dark bg-info flex-column flex-md-row bd-navbar">
		    <a class="navbar-brand" href="#">
		    	<img src="../resources/image/icons8-member-50.png" width="25" height="25" alt=""></img>
		      	#{customerApplication.username} - Customer  List</a>
		    <div class="navbar-nav-scroll">
			   <ul class="navbar-nav bd-navbar-nav flex-row">
			      <li class="nav-item active"><a class="nav-link" href="#">Customer  &nbsp; &nbsp;</a></li>
			      <li class="nav-item"><a class="nav-link" href="contactlist.xhtml">Contact  &nbsp; &nbsp;</a></li>
			      <li class="nav-item"><a class="nav-link" href="industrylist.xhtml">Industry  &nbsp; &nbsp;</a></li>
			      <li class="nav-item"><a class="nav-link" href="stafflist.xhtml">User  </a></li>
			    </ul>
			</div> 
			<a href="${pageContext.request.contextPath}/Assignment-war/logout" 
			class="btn btn-outline-light btn-sm my-2 my-sm-0"
			onclick="if (!confirm('Are you sure to log out?')) return false;">
			Logout</a>
		</div>
		
		<br/>
        
        <h:form id="MyForm1">
        	
        	<table id="MyTable1" class="table table-sm table-bordered table-striped">
        		<!-- For each customer in ArrayList... -->
        		<!-- column name -->
        		<tr>
        			<td>
                        <h:outputLabel id="Id" value="Id"  />
                    </td>
                    <td>
                        <h:outputLabel id="Name" value="Name"  />
                    </td>
                    <td>
                        <h:outputLabel id="Address" value="Address"/>
                    </td>
                    <td>
                        <h:outputLabel id="Option" value="Option"/>
                    </td>

        		</tr>
        	
				<!-- table content -->
        		<ui:repeat id="Myrepeat" value="#{customerApplication.customers}"  var="customer" varStatus="status">

	                <tr onclick="document.getElementById('MyForm:principle').value = document.getElementById('MyForm:Myrepeat:#{status.index}:outPrice').textContent">
	                    <td>
	                        <h:outputText id="customerID" value="#{customerApplication.customers.get(status.index).customerId}"/>
	                    </td>
	                    <td>
	                        <h:outputText id="outName" value="#{customerApplication.customers.get(status.index).customerName}"  />
	                    </td>
	                    <td>
	                        <h:outputText id="outAddress" value="#{customerApplication.customers.get(status.index).address}"/>
	                    </td>

						<!-- FUNCTION FOR EACH CUSTOMER -->
	                    <td>
	                        <h:link value="View" class="btn btn-outline-info btn-sm" outcome="customerdetail.xhtml">
	                        <!-- pass the parameter to next page, the param name is customerID, and the value is index + 1.
	                        You can get the value from next page using the indexController -->
	                        <f:param name="customerID" value="#{status.index + 1}"/>
	                        </h:link>
							&nbsp;
	                        <h:link value="Edit" class="btn btn-outline-info btn-sm" outcome="customeredit.xhtml">
	                        <!-- pass the parameter to next page, the param name is customerID, and the value is index + 1.
	                        You can get the value from next page using the indexController -->
	                        <f:param name="customerID" value="#{status.index + 1}"/>
	                        </h:link>
	                        &nbsp;
	                        <h:commandLink value="De-assign Staff"  class="btn btn-outline-dark btn-sm"
	                        action="#{customerManagedBean.deassignStaff(customerApplication.customers.get(status.index).customerId)}"
	                        onclick="if (!confirm('Are you sure to de-assign staff? \nYou can re-assign staff later')) return false;"
	                        rendered="#{customerManagedBean.checkStaff(customerApplication.customers.get(status.index).customerId)}"/>
	                        &nbsp;
	                        <h:commandLink value="Delete" class="btn btn-outline-danger btn-sm"
	                        action="#{customerRemove.customerRemove(customerApplication.customers.get(status.index).customerId)}" 
	                        disabled="#{customerApplication.customers.get(status.index).customerId == null}"
	                        onclick="if (!confirm('Are you sure to delete it? \nAll related Contacts will also be deleted!')) return false;">
                            </h:commandLink>
	                        
	                        <h:outputText value=" "/>
	                    </td>
	
	                </tr>

                </ui:repeat>
        	
        	</table>
        	
	
        	<!-- GENERAL FUNCTION : add / search /...... -->
        	<div>
        		<h:commandButton id="add" value="Add" action="customeradd.xhtml" class="btn btn-info" />
				&nbsp; &nbsp;
	        	<h:commandButton id="viewAll" value="View All" action="#{customerSearch.searchAll()}" class="btn btn-info" >

	            </h:commandButton>

	            &nbsp; &nbsp;
				<button onclick="myFunction()" class="btn btn-info">Count</button>
            	<p id="countResult"></p>	            
	            
        	</div>
        	
        	<div>
        		<!-- https://stackoverflow.com/questions/5288267/how-to-add-a-message-to-a-specific-component-from-jsf-backing-bean -->
				<h:outputText id="test" binding="#{customerRemove.component}"/>
				<h:message for="test" infoClass="info" globalOnly ="true" style="color:blue"/>
        	</div>
        	
        	<br/>
        	
       	 </h:form>
       	 <h:form id="MyForm2">
       	 
        	<div>
        		
        		<h:inputText value="#{customerSearch.searchByInt}" 
        		id="searchById" required="true"
        		onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "  />
        		&nbsp;
        		<h:commandButton id="searchId" value="Search by Id" 
        		action="#{customerSearch.searchCustomerById(customerSearch.searchByInt)}" 
        		class="btn btn-info" >
                    <f:param name="customerID" value="#{status.index + 1}"/>
                </h:commandButton>
                &nbsp; &nbsp;
              
            </div>
        	
        	<br/>
       	 </h:form>
       	 <h:form id="MyForm3">
        		
        	<div>  
                <h:selectOneMenu id="contact" value="#{contactSearch.contactId}" >
	                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
	                <f:selectItems value="#{contactManagedBean.allContacts}" var="c"
	                                itemLabel="#{c.name}" itemValue="#{c.contactId}" />
	            </h:selectOneMenu>
	            &nbsp;
	            <h:commandButton id="searchByContact" value="Search by Contact" 
	            action="#{customerSearch.searchCustomerByContactId(contactSearch.contactId)}" 
	            class="btn btn-info" >
	                <f:param name="customerID" value="#{status.index + 1}"/>
	            </h:commandButton>
	            &nbsp; &nbsp;
	            <h:selectOneMenu id="staff" value="#{staffSearch.staffId}" >
	                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
	                <f:selectItems value="#{staffManagedBean.allStaffs}"
								var="c" itemLabel="#{c.username}" itemValue="#{c.id}" />
	            </h:selectOneMenu>
	            &nbsp;
	            <h:commandButton id="searchByStaff" value="Search by Staff" 
	            action="#{customerSearch.searchCustomerByStaffId(staffSearch.staffId)}" 
	            class="btn btn-info" >
	                <f:param name="customerID" value="#{status.index + 1}"/>
	            </h:commandButton>
                
        	</div>
        	
        	<br/>
       	 </h:form>
       	 <h:form id="MyForm4">
        		
        	<div>
        		<h:selectOneMenu id="industry" value="#{industrySearch.industryId}" >
	                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
	                <f:selectItems value="#{industryManagedBean.allIndustries}" var="c"
	                                itemLabel="#{c.industryType}" itemValue="#{c.industryId}" />
	            </h:selectOneMenu> 
	            &nbsp;
	            <h:inputText value="#{customerSearch.yearRegistered}" 
        		id="searchByYear"
        		pt:placeholder="Year Registered"
        		onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "  />
        		&nbsp;
        		<h:commandButton id="searchByYearAndIndustry" value="Search by Industry / Year" 
	            action="#{customerSearch.searchCustomerByYearAndIndustry(customerSearch.yearRegistered, industrySearch.industryId)}" 
	            class="btn btn-info" >
	                <f:param name="customerID" value="#{status.index + 1}"/>
	            </h:commandButton>   	
        	
        	</div>

        </h:form>
	
	</div>
</body> 
</html>